### ISSUE TITLE
TODO List For Girls Rise Up: STRENGTH 

### ISSUE THREAD

**Issue by Huriphoonado** [DancingAndDabbing/danceON#15]
### Goals Before Tuesday
- [ ] Fix object size to be locked
- [ ] Webcam Sizing
- [ ] Solve classifier Message Bug for longer videos
- [ ] Remove docs link
- [ ] Footer
- [ ] Cache
- [ ] Use teachable machine classifier in editor "when" statements
- [ ] StrokeWeight support
- [ ] function overrides to accept lists as arguments
- [ ] Frame animation support extended to lists and strings (currently just numbers)
- [ ] Documentation and Examples Finished in Sidebar
- [ ] Settings Palette in Controls window (e.g. text resize)
- [ ] Mute button

### Nice-To-Have Progress
- [ ] Better Error Messages
- [ ] Filter
- [ ] Autocorrect
- [ ] Upload graphics
